name: Streamlined-DevSecOps-Pipeline

on:
  push:
    branches:
      - pipeline

jobs:
  streamlined-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        run: echo "Checked out source code"

      - name: Build
        run: echo "Code build completed"

      - name: Test
        run: echo "Testing phase finished"

      - name: Deploy
        run: |
          echo "Deployment completed"
          java -version
          python --version

