name: DevSecOps Foundations

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        run: echo "Checkout of code is done"

  build:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Build
        run: echo "Code build is done"

  sast:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Static Application Security Testing (SAST)
        run: echo "Running SAST scan..."

  sca:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Software Composition Analysis (SCA)
        run: echo "Running SCA to check for vulnerable libraries..."

  container-scan:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Container Image Scan
        run: echo "Scanning container image for vulnerabilities..."

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Test
        run: echo "Testing is done"

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Dev Env Deployment 
        run: echo "Deploying to the dev env"

  dast:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Dynamic Application Security Testing (DAST)
        run: |
          echo "Dast scan completed"
          java -version
          python --version
