name: Streamlined-DevSecOps-Pipeline

on:
  push:
    branches:
      - pipeline

jobs:
  streamlined-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        run: echo "Checked out source code"

      - name: Build
        run: echo "Code build completed"

      - name: Test 
        script:
          - echo "Security Testing Continer"
          - docker pull bkimminich/juice-shop
          - docker run --name containersecurity -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image bkimminich/juice-shop

      - name: Deploy
        run: |
          echo "Deployment completed"
          java -version
          python --version

